#!/usr/bin/env bash

# Fail fast
set -e
# DEBUG
# set -x

usage() {
cat <<-"END"
Operate an OpenID Connect Provider

Usage:
  oidc-cli (baseUrl) create-client

Options:
  -h --help           Show this help.
  -k --insecure       Pass -k to cURL. Allow insecure SSL  

Patterns:
  oidc-cli https://accounts.t402.livefyre.com create-client
END
}

# http://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash
for i in "$@"
do
case $i in
    -h|--help)
    usage
    exit
    ;;
    # -a=*|--auth=*)
    #   Authorization="${i#*=}"
    #   shift # past argument=value
    # ;;
    # -k|--insecure)
    #   curl_opts="-k $curl_opts"
    # ;;
    # *)
    #   # unknown option
    # ;;
esac
done

base_url=$1

command=$2
if [[ $command != "create-client" ]]; then
  >&2 echo "Only supported command is create-client, but you provided $command"
  >&2 usage
  exit 1
fi

./create-client "$@"
