#!/usr/bin/env bash

# Fail fast
set -e
# DEBUG
# set -x

usage() {
cat <<-"END"
List the Clients stored on the filesystem

Usage:
  list-clients [baseUrl]

Options:
  -h --help           Show this help.

Patterns:
  list-clients "https://accounts.fy.re"
END
}

# http://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash
for i in "$@"
do
case $i in
    -h|--help)
    usage
    exit
    ;;
    *)
      # unknown option
    ;;
esac
done

this_script=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)/`basename "${BASH_SOURCE[0]}"`
this_dir=$(dirname $this_script)
oidc_root_dir=$(dirname $this_dir)
clients_dir=$oidc_root_dir/clients
base_url=$1

if [[ "$base_url" == "" ]]; then
  find $clients_dir -mindepth 2 -maxdepth 2
  exit
fi

# extract the protocol
proto="$(echo $base_url | grep :// | sed -e's,^\(.*://\).*,\1,g')"
# remove the protocol
op_host="$(echo ${base_url/$proto/})"
op_clients_dir=$clients_dir/$op_host

find $op_clients_dir -mindepth 1 -maxdepth 1

exit 0
